### ISSUE TITLE
Feedback on Research document

### ISSUE THREAD

**Issue by gclynch** [Siemens3/4thYearProject#1]
English too informal
Distinct lack of clarity in the writing
Lack of clarity with respect to proposed functionality
Lack of clarity with respect to technical architecture
Typos
What is Morph?
Proof read
Lack of detail with respect to technical architecture
i.e. SQL Azure, ADO.Net Entity Framework, LINQ, ASP.Net Web API, Azure cloud services, authentication,
Windows Phone 8

**Comment by Siemens3** [comment]
Will fix all this after meetings this Wednesday.
